### ISSUE TITLE
.rar/.zip filetype recognition

### ISSUE THREAD

**Issue by spidermitch0** [azuravian/playnite-LocalInstallButton#13] opened 2023-11-10 23:20 UTC
Alot of indie titles and visual novels are zipped up game files via rar / zip.  The Local install button errors out when pointing it to anything other than .ISO or .EXE.  While most of the rar/zip files can be converted to a self-extracting EXE, LARGE rared/zipped files can't be converted to a self-extracting .exe. 

You CAN point directly to the .rar / .zip file and use whatever app is associated with the filetype to extract the files via putting a link in the "Links" section of the game entry, but is inconsistent with all other install button .exes and .isos your wonderful plugin allows for.

Would it be possible to allow the plugin to point to a .zip and .rar file, let the user extract the files, then simply select the game's executable (as a last step like the current functionality of setup.exe's do?)

**Comment by azuravian** [comment] 2024-01-26 00:19
Absolutely, will add this soon.

**Comment by Koriebonx98** [comment] 2024-05-18 19:36
any updates on this? 

for now i have set up:
 emu = winrar,
  rom = zip,rar
  sep profile argu:
  x -o+ "{ImagePath}" "D:\Games"
  
  change d drive with other driver letters one per profile
  
  auto scan, set up a folder called "Installer" followed by platformName e.g xbox 360, this wherer zip\rar files are
  
  con, for now you click the play button to run set up.
  emulated games auto detect. 
  pc games require manual work

**Comment by azuravian** [comment] 2024-05-21 16:22
Yes, I'll work this week on adding this functionality to the new plugin I'm creating that will be replacing this one.  I think it will be ready to launch in the next couple of weeks.

**Comment by Koriebonx98** [comment] 2024-05-22 00:49
> Yes, I'll work this week on adding this functionality to the new plugin I'm creating that will be replacing this one. I think it will be ready to launch in the next couple of weeks.

Can you do it so if we have action called “Download” set up then when we click install if install file don’t exsist then use the download?

**Comment by spidermitch0** [comment] 2024-05-23 16:22
> Yes, I'll work this week on adding this functionality to the new plugin I'm creating that will be replacing this one. I think it will be ready to launch in the next couple of weeks.

This is excellent news!  Currently my library has quite a few "unzip to install" type of games; mostly indie.  I'm having to point to the .zip/.rar path in the LINKS location of the game details.  Then when I go to install said game, I have to remember that the normal "Install" button won't work & instead click on that .zip/.rar link I created.  All other games use this add-in to point to the .exe/.iso installs on my NAS (which is a HUGE WIN / THANK YOU!!!!), but definitely letting us point to a .zip/.rar just so it would open up the winrar (or whatever app you have associated with that filetype) would be awesome!  Not to mention add consistency to the overall process of installation with the install button.


Anyway, super excited about this & I'm up for testing it out if you need someone to do so!

**Comment by azuravian** [comment] 2024-05-23 21:46
Let's move any discussion here to issue #15.
It covers other functionality that will be part of the new plugin as well.

Duplicate of #15

**Closed as completed by azuravian** 2024-05-23 21:46 UTC
